### ISSUE TITLE
PDF files in version control

### ISSUE THREAD

**Issue by ben-marshall** [MVSE-Outreach/LaTeX-Worksheet-Templates#3]
The repository itself is already 30MB in size, expanding to 60MB when extracted. This is mostly due to having to version large image files, and large image files _inside_ PDF files, which just appear as binary blobs to git.

The built PDF files probably shouldn't be inside version control. If we want a place where we can view them as reference, we should have a separate folder called "/pre-built/" or some such, with the latest acceptable versions of the PDF's, so they aren't updated with every single commit.

**Comment by EdNutting** [comment]
True true - will be sorted on Monday
