### ISSUE TITLE
License

### ISSUE THREAD

**Issue by willprice** [MVSE-Outreach/LaTeX-Worksheet-Templates#4]
It might be prudent to actually put these under a license rather than vaguely list what is acceptable. I suggest [Creative Commons Share Alike](https://creativecommons.org/licenses/by-sa/4.0/), this allows others to modify the resources, but they have to also release under share alike. Commercial use is permitted (Anyone getting paid to teach kids tech).

Thoughts?

**Comment by EdNutting** [comment]
Yeah sounds good, will deal with this on Wednesday.

**Comment by EdNutting** [comment]
Applied suggested license in f0da3e00052fe5dfe65b86bce79967d2e1b8aa68
